server:
  port: ${PORT}

spring:
  flyway:
    locations: classpath:/db/migrations
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

